export const GENRES = [
	"Crime Fiction",
	"Business",
	"Entrepreneurship",
	"Management",
	"Health",
	"Family",
	"Personal Development",
	"Relationships",
	"Analysis & Strategy",
	"Fantasy",
	"Science Fiction",
	"Dystopian",
	"Action & Adventure",
	"Mystery",
	"Horror",
	"Thriller & Suspense",
	"Historical Fiction",
	"Romance",
	"Women's Fiction",
	"LGBTQ+",
	"Contemporary Fiction",
	"Literary Fiction",
	"Magical Realism",
	"Graphical Novel",
	"Short Story",
	"Young Adult",
	"New Adult",
	"Children's",
	"Memoir & Autobiography",
	"Biography",
	"Food & Drink",
	"Art & Photography",
	"Self-Help",
	"History",
	"Travel",
	"True Crime",
	"Humor",
	"Essays",
	"Guide / How-To",
	"Religion & Spirituality",
	"Humanities & Social Sciences",
	"Parenting & Families",
	"Science & Technology",
	"Society & Culture"
]