export const GENRES = {
    "fantasy" : 1,
    "science fiction" : 2,
    "adventure" : 3,
    "romance" : 4,
    "mystery" : 5,
    "horror" : 6,
    "thriller" : 7,
    "historical fiction" : 8,
    "children's fiction" : 9,
    "autobiography" : 10,
    "biography" : 11,
    "cooking" : 12,
    "art" : 13,
    "selfhelp" : 14,
    "inspirational" : 15,
    "health & fitness" :16,
    "history" : 17,
    "humor" : 18,
    "business" : 19,
    "travel" : 20,
};
