export const GENRES = [
    "Adventure",
    "Art",
    "Autobiography",
    "Biography",
    "Business",
    "Children's",
    "Children's History",
    "Classics",
    "Comics",
    "Contemporary Fiction",
    "Cookbooks",
    "Crime Fiction",
    "Drama",
    "Dystopian",
    "Essays",
    "Family",
    "Fantasy",
    "Fiction",
    "Food & Drink",
    "Graphic Novels",
    "Guide / How-To",
    "Health",
    "Historical Fiction",
    "History",
    "Horror",
    "Humanities & Social Sciences",
    "Humor",
    "LGBTQ+",
    "Literary Fiction",
    "Magical Realism",
    "Management",
    "Memoir",
    "Music",
    "Mystery",
    "New Adult",
    "Parenting & Families",
    "Personal Development",
    "Philosophy",
    "Photography",
    "Poetry",
    "Psychological Thrillers",
    "Psychology",
    "Relationships",
    "Religion & Spirituality",
    "Romance",
    "Science",
    "Science & Technology",
    "Science Fiction",
    "Self Help",
    "Short Story",
    "Society & Culture",
    "Sports",
    "Thriller",
    "Travel",
    "Women's Fiction",
    "Young Adult",
];
