export const LANGUAGES = [
  "EN - English",
  "ZH - Chinese",
  "DE - German",
  "ES - Spanish",
  "JA - Japanese",
  "RU - Russian",
  "FR - French",
  "KO - Korean",
  "IT - Italian",
  "NL - Dutch",
  "PT - Portugese",
  "HI - Hindi",
  "PL - Polish",
  "DA - Danish",
  "BN - Bangla",
];
