//export const BASE_URL = "http://localhost:8080";
export const BASE_URL = "https://server.nalnda.com";
export const ENDPOINTS = {
  COLLECTION: {
    COLLECTION: BASE_URL + "/api/collections",
    SPECIFIC_COLLECTION: BASE_URL + "/api/collections/books",
    GENRES: BASE_URL + "/api/collections/genres",
    USER_BOOKS_GENRES: BASE_URL + "/api/collections/user/genres",
  },
  USER: {
    USER_LOGIN: BASE_URL + "/api/user/oauth/login",
    USER_PROFILE: BASE_URL + "/api/user/profile",
    USER_BOOK: BASE_URL + "/api/user/book",
    USER_EDIT_PROFILE: BASE_URL + "/api/user/profile",
    USER_PICTURE: BASE_URL + "/api/user/profile/pic",
    USER_CHECK_USER: BASE_URL + "/api/book/checkUser",
    USER_WALLET_CONNECT: BASE_URL + "/api/user/wallet",
    USER_SURVEY_FEEDBACK: BASE_URL + "/api/user/feedback",
  },

  BOOK: {
    BOOK_PUBLISHED: BASE_URL + "/api/user/books/published",
    BOOK_LISTING: BASE_URL + "/api/user/books/listing",
    BOOK_SEARCH: BASE_URL + "/api/book/search",
    BOOK_DA_SCORE: BASE_URL + "/api/book/get-dascore",
    BOOK_OWNED: BASE_URL + "/api/user/books/owned",
    USER_BOOK: BASE_URL + "/api/user/book",
    BOOK_OFFERS: BASE_URL + "/api/book/book-offers",
    BOOK_OWNER: BASE_URL + "/api/book/owner",
    BOOK_QUOTE: BASE_URL + "/api/book/quoted",
    BOOK_QUOTES: BASE_URL + "/api/book/quotes",
    BOOK_REVIEWS: BASE_URL + "/api/book/reviews",
    BOOK_LIKED: BASE_URL + "/api/book/liked",
    BOOK_CRYPTO_ORDER: BASE_URL + "/api/book/crypto/order/wc",
    BOOK_CRYPTO_ORDER_FAILED: BASE_URL + "/api/book/crypto/error/bc",
    BOOK_CRYPTO_MINE: BASE_URL + "/api/book/crypto/mine",
    BOOK_COPIES: BASE_URL + "/api/book/copies",
    BOOK_CRYPTO_PURCHASE: BASE_URL + "/api/book/purchase",
    BOOKS: BASE_URL + "/api/book",
    BOOK_TOTAL_READER_COUNT: BASE_URL + "/api/reader/total-reader-count",
    BOOK_READER_COUNT: BASE_URL + "/api/reader/count",
    BOOK_READER_READ_TIME: BASE_URL + "/api/reader/total-read-time",
    USER_READ_TIME: BASE_URL + "/api/reader/read-time",
    BOOK_SUBMARINE: BASE_URL + "/api/book/submarine",
    BOOK_PUBLISH: BASE_URL + "/api/book/publish",
    TRENDING_BOOKS: BASE_URL + "/api/book/trending-books",
    BOOK_LIKE: BASE_URL + "/api/book/likes",
  },
};
